### ISSUE TITLE
Segfault on literal characters

### ISSUE THREAD

**Issue by ontholerian** [rsyslog/liblognorm#66] opened 2015-06-01 21:24 UTC
If a logfile happens to have certain characters at the start of a parser, it can cause liblognorm to segfault.

Example that demonstrates the issue:
``$ cat example.rb``
rule=:%foo:word% %bar:number% %baz:word%
``$ echo -e "a 2 c" | lognormalizer -r example.rb -e json``
{ "baz": "c", "bar": "2", "foo": "a" }
``$ echo -e "a \xf9 c" | lognormalizer -r example.rb -e json``
Segmentation fault (core dumped)

After digging through the code, looks like its caused by an improper casting of a signed char to an integer, where an unsigned char is expected. All of the code is in ``ptree.c`` and regards how the use of  ``ln_ptree->subtree`` is index-referenced. Note that in ``ln_buildPTree``, the variable used to index ``tree->subtree`` is ``c``, which is an ``unsigned char *``. However, in ``ln_normalizeRec`` where it checks if the next parser should be a literal, it casts a value from ``str`` -- a ``const char *`` -- to ``int``.

A char of ``\xf9`` casts to value 249 as an unsigned char and to value -7 as an integer, so the casting will take you to two different indexes in the ``tree->subtree`` array, and one of those has a very undesirable result.

**Comment by ontholerian** [comment] 2015-06-10 01:07
See pull request #67

**Comment by janmejay** [comment] 2015-06-10 06:26
Can you please add a test to cover the bug?

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment] 2015-06-10 07:39
FYI: this is most probably a duplicate of #57

**Comment by rgerhards** [comment] 2015-06-11 14:51
Sorry for the noise, this is NOT a dup of #57.

**Comment by rgerhards** [comment] 2015-06-23 06:21
merged without a test, so this may re-occur in the future

**Closed** 2015-06-23 06:20 UTC
