### ISSUE TITLE
rule starting with literal causes unparsed data

### ISSUE THREAD

**Issue by marnao** [rsyslog/liblognorm#57] opened 2015-05-05 20:00 UTC
This rule works by itself:
$ cat rules.db
#rule=:%foo:char-sep:|%|%bar:char-sep:|%|%baz:char-sep:|%
rule=:foo bar baz

$ echo "foo bar baz" | lognormalizer -r rules.db -e json
{ }

And the other rule works by itself:
$ cat rules.db
rule=:%foo:char-sep:|%|%bar:char-sep:|%|%baz:char-sep:|%
#rule=:foo bar baz

$ echo "foo|bar|baz" | lognormalizer -r rules.db -e json
{ "baz": "baz", "bar": "bar", "foo": "foo" }

When combined, the rule that starts with a literal does not work correctly:
$ cat rules.db
rule=:%foo:char-sep:|%|%bar:char-sep:|%|%baz:char-sep:|%
rule=:foo bar baz

$ echo "foo bar baz" | lognormalizer -r rules.db -e json
{ "originalmsg": "foo bar baz", "unparsed-data": "" }

A temporary workaround is to make the beginning of the rule a field selector like word. I don't see any reason why these should not work together though, unless I'm missing something.

Thanks for taking a look.

**Comment by rgerhards** [comment] 2015-05-08 11:08
It's definitely a bug.

**Comment by rgerhards** [comment] 2015-05-08 11:14
I've committed a temporary fix. It solves your issue, but there is a problem with the descent testbench test. I need to investigate that further; expect updates to the patch. In any case, if it's urgent and you do not use descent, you can most probably use the patch without any problems.

**Comment by rgerhards** [comment] 2015-05-08 12:28
@janmejay if possible, could you please check why the descent parser test fails in the testbench. I have looked at it, and it looks like the "prased" parameter (number of characters successfully processed) invalidly returns 0.

**Comment by janmejay** [comment] 2015-05-08 14:57
Will check.

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by marnao** [comment] 2015-05-08 15:51
Thanks for the patch! We don't have any rules that use descent right now so that's not a problem at all.

**Comment by janmejay** [comment] 2015-05-09 17:59
Rainer,

All tests seem to pass for me. Can you share the change-ref?

I tried on 50d8be615dcda038c23a9ed2bb9bdb1e10abe6d5.

On Fri, May 8, 2015 at 9:21 PM, marnao <notifications@github.com> wrote:

> Thanks for the patch! We don't have any rules that use descent right now
> so that's not a problem at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/liblognorm/issues/57#issuecomment-100278377>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment] 2015-05-09 18:04
Found the branch on your fork, running the testsuite.

On Sat, May 9, 2015 at 11:29 PM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> Rainer,
>
> All tests seem to pass for me. Can you share the change-ref?
>
> I tried on 50d8be615dcda038c23a9ed2bb9bdb1e10abe6d5.
>
> On Fri, May 8, 2015 at 9:21 PM, marnao <notifications@github.com> wrote:
>
>> Thanks for the patch! We don't have any rules that use descent right now
>> so that's not a problem at all.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rsyslog/liblognorm/issues/57#issuecomment-100278377>.
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment] 2015-05-09 18:09
Have the failure reproduced.

On Sat, May 9, 2015 at 11:34 PM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> Found the branch on your fork, running the testsuite.
>
> On Sat, May 9, 2015 at 11:29 PM, singh.janmejay <singh.janmejay@gmail.com>
> wrote:
>
>> Rainer,
>>
>> All tests seem to pass for me. Can you share the change-ref?
>>
>> I tried on 50d8be615dcda038c23a9ed2bb9bdb1e10abe6d5.
>>
>> On Fri, May 8, 2015 at 9:21 PM, marnao <notifications@github.com> wrote:
>>
>>> Thanks for the patch! We don't have any rules that use descent right now
>>> so that's not a problem at all.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/rsyslog/liblognorm/issues/57#issuecomment-100278377>
>>> .
>>>
>>
>>
>>
>> --
>> Regards,
>> Janmejay
>> http://codehunk.wordpress.com
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment] 2015-05-10 14:19
Rainer,

I wrote a test to reproduce the problem(originally to ensure I don't break
it while fixing descent). Bu, it doesn't fail in-spite of reverting your
change.

Have a look at this:
https://travis-ci.org/janmejay/liblognorm/builds/61970097

This branch:
https://github.com/janmejay/liblognorm/commits/fix-parser-literal

The commit creates a test, which executes all 3 scenarios that Marnao
mentioned, and it still passes with your commit reverted.


On Sat, May 9, 2015 at 11:39 PM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> Have the failure reproduced.
>
> On Sat, May 9, 2015 at 11:34 PM, singh.janmejay <singh.janmejay@gmail.com>
> wrote:
>
>> Found the branch on your fork, running the testsuite.
>>
>> On Sat, May 9, 2015 at 11:29 PM, singh.janmejay <singh.janmejay@gmail.com
>> > wrote:
>>
>>> Rainer,
>>>
>>> All tests seem to pass for me. Can you share the change-ref?
>>>
>>> I tried on 50d8be615dcda038c23a9ed2bb9bdb1e10abe6d5.
>>>
>>> On Fri, May 8, 2015 at 9:21 PM, marnao <notifications@github.com> wrote:
>>>
>>>> Thanks for the patch! We don't have any rules that use descent right
>>>> now so that's not a problem at all.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/rsyslog/liblognorm/issues/57#issuecomment-100278377>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Regards,
>>> Janmejay
>>> http://codehunk.wordpress.com
>>>
>>
>>
>>
>> --
>> Regards,
>> Janmejay
>> http://codehunk.wordpress.com
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment] 2015-05-11 07:12
Sorry, been more or less offline of the weekend. It's strange, as I can reproduce the issue and also see that the code actually is wrong (it uses an invalid offset in literal checking if a parser failed with -1). Let me dig into your branch and see what's going on here...

**Comment by rgerhards** [comment] 2015-07-14 12:39
@janmejay  Well, without the patch there definitely is a bug inside the code, even if it is not reproducible in all environments.

**Comment by rgerhards** [comment] 2015-07-14 15:11
I now worked with the failing test intensely. As noted in #78, something is fishy with the test. Nevertheless, it fails as follows when the proposed patch is added:

```
tail-field not populated
Out:
{ "originalmsg": "10.20.30.40 foo", "unparsed-data": "10.20.30.40 foo" }
JSONs weren't equal. 
	Expected: 
		{ "originalmsg": "10.20.30.40 foo", "unparsed-data": "" }
	Actual: 
		{ "originalmsg": "10.20.30.40 foo", "unparsed-data": "10.20.30.40 foo" }
```

Looking at more depth, I think the previous state is incorrect, and the patch just corrected that. Because it makes absolutely no sense to have empty unparsed-data in this failure case. So I think the previous unparsed-data was just copied "as is" and did not look important enough to think hard about it. So I will now change it to the correct value.

**Comment by rgerhards** [comment] 2015-07-14 15:12
@janmejay If you disagree, please let me know. Otherwise I'll craft a new release on Friday (this was the blocker for the release).

**Comment by janmejay** [comment] 2015-07-14 16:03
Well, it a negative-test, so exact error doesn't matter as much. I guess we
should go-ahead with the change. This can't break something which is
already working for a user, because its testing behaviour with a broken
config anyway.

I raised it because environment-sensitive behaviour was kind-of unexpected
in that area. I wasn't concerned about its impact on that particular test's
exact failure mode(as long as it doesn't successfully parse, and lognorm
doesn't crash, the test is effectively passing). It was just concerned
about enc-sensitive stuff hitting us in that area.

On Tue, Jul 14, 2015 at 8:42 PM, Rainer Gerhards <notifications@github.com>
wrote:

> @janmejay <https://github.com/janmejay> If you disagree, please let me
> know. Otherwise I'll craft a new release on Friday (this was the blocker
> for the release).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/liblognorm/issues/57#issuecomment-121277994>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment] 2015-07-14 16:15
ok, thanks for the quick feedback. So I think I'll release asap.

**Comment by janmejay** [comment] 2015-07-14 16:19
Makes sense.

On Tue, Jul 14, 2015 at 9:45 PM, Rainer Gerhards <notifications@github.com>
wrote:

> ok, thanks for the quick feedback. So I think I'll release asap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/liblognorm/issues/57#issuecomment-121294157>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Closed** 2015-07-14 16:21 UTC
Labels: bug
